name: CI

on: [push]

jobs:
  static_checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m venv venv
        . "./venv/bin/activate"
        pip install .[test]
        # Make venv persistent across steps
        echo "PATH=$PATH" >> "$GITHUB_ENV"
        echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> "$GITHUB_ENV"
    - name: Lint with Pylint
      run: pylint --score=n not_my_board
    - name: Check format with Black
      run: black --check --quiet not_my_board
    - name: Check import statement order with isort
      run: isort --check not_my_board
    - name: Check spelling
      run: git ls-files -z | xargs -0 -- codespell
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
    - name: Create test VM image
      run: sudo ./scripts/vmctl makeimg
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install qemu-system
        python -m venv venv
        . "./venv/bin/activate"
        pip install .[test]
        # Make venv persistent across steps
        echo "PATH=$PATH" >> "$GITHUB_ENV"
        echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> "$GITHUB_ENV"
    - name: Run tests
      run: pytest -s
