name: Static Checks

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        pip install hatch
        hatch env create
        # Make venv persistent across steps
        . "$(hatch env find)/bin/activate"
        echo "PATH=$PATH" >> "$GITHUB_ENV"
        echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> "$GITHUB_ENV"
    - name: Lint with Pylint
      run: pylint --score=n not_my_board
    - name: Check format with Black
      run: black --check --quiet not_my_board
    - name: Check import statement order with isort
      run: isort --check not_my_board
